export interface CatalogOption {
  code: string;
  label: string;
}

// Source: DTE/Catálogos - Facturación Electrónica.xlsx, CAT-020 País.
export const CAT020_COUNTRIES = [
  { code: "AF", label: "Afganistán" },
  { code: "AX", label: "Aland" },
  { code: "AL", label: "Albania" },
  { code: "DE", label: "Alemania" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AI", label: "Anguila" },
  { code: "AQ", label: "Antártica" },
  { code: "AG", label: "Antigua y Barbuda" },
  { code: "AW", label: "Aruba" },
  { code: "SA", label: "Arabia Saudita" },
  { code: "DZ", label: "Argelia" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaiyán" },
  { code: "BS", label: "Bahamas" },
  { code: "BH", label: "Bahrein" },
  { code: "BD", label: "Bangladesh" },
  { code: "BB", label: "Barbados" },
  { code: "BE", label: "Bélgica" },
  { code: "BZ", label: "Belice" },
  { code: "BJ", label: "Benin" },
  { code: "BM", label: "Bermudas" },
  { code: "BY", label: "Bielorrusia" },
  { code: "BO", label: "Bolivia" },
  { code: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
  { code: "BA", label: "Bosnia-Herzegovina" },
  { code: "BW", label: "Botswana" },
  { code: "BR", label: "Brasil" },
  { code: "BN", label: "Brunei" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "BT", label: "Bután" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KY", label: "Caimán, Islas" },
  { code: "KH", label: "Camboya" },
  { code: "CM", label: "Camerún" },
  { code: "CA", label: "Canadá" },
  { code: "CF", label: "Centroafricana, República" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CY", label: "Chipre" },
  { code: "VA", label: "Ciudad del Vaticano" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoras" },
  { code: "CG", label: "Congo" },
  { code: "CI", label: "Costa de Marfil" },
  { code: "CR", label: "Costa Rica" },
  { code: "HR", label: "Croacia" },
  { code: "CU", label: "Cuba" },
  { code: "CW", label: "Curazao" },
  { code: "DK", label: "Dinamarca" },
  { code: "DM", label: "Dominica" },
  { code: "DJ", label: "Djiboutí" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egipto" },
  { code: "SV", label: "El Salvador" },
  { code: "AE", label: "Emiratos Árabes Unidos" },
  { code: "ER", label: "Eritrea" },
  { code: "SK", label: "Eslovaquia" },
  { code: "SI", label: "Eslovenia" },
  { code: "ES", label: "España" },
  { code: "US", label: "Estados Unidos" },
  { code: "EE", label: "Estonia" },
  { code: "ET", label: "Etiopía" },
  { code: "FJ", label: "Fiji" },
  { code: "PH", label: "Filipinas" },
  { code: "FI", label: "Finlandia" },
  { code: "FR", label: "Francia" },
  { code: "GA", label: "Gabón" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "GH", label: "Ghana" },
  { code: "GI", label: "Gibraltar" },
  { code: "GD", label: "Granada" },
  { code: "GR", label: "Grecia" },
  { code: "GL", label: "Groenlandia" },
  { code: "GP", label: "Guadalupe" },
  { code: "GU", label: "Guam" },
  { code: "GT", label: "Guatemala" },
  { code: "GF", label: "Guayana Francesa" },
  { code: "GG", label: "Guernsey" },
  { code: "GN", label: "Guinea" },
  { code: "GQ", label: "Guinea Ecuatorial" },
  { code: "GW", label: "Guinea-Bissau" },
  { code: "GY", label: "Guyana" },
  { code: "HT", label: "Haití" },
  { code: "HN", label: "Honduras" },
  { code: "HK", label: "Hong Kong" },
  { code: "HU", label: "Hungría" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IQ", label: "Irak" },
  { code: "IE", label: "Irlanda" },
  { code: "BV", label: "Isla Bouvet" },
  { code: "IM", label: "Isla de Man" },
  { code: "NF", label: "Isla Norfolk" },
  { code: "IS", label: "Islandia" },
  { code: "CX", label: "Islas Navidad" },
  { code: "CC", label: "Islas Cocos" },
  { code: "CK", label: "Islas Cook" },
  { code: "FO", label: "Islas Faroe" },
  { code: "GS", label: "Islas Georgias d. S.-Sandwich d. S." },
  { code: "HM", label: "Islas Heard y McDonald" },
  { code: "FK", label: "Islas Malvinas (Falkland)" },
  { code: "MP", label: "Islas Marianas del Norte" },
  { code: "MH", label: "Islas Marshall" },
  { code: "PN", label: "Islas Pitcairn" },
  { code: "TC", label: "Islas Turcas y Caicos" },
  { code: "UM", label: "Islas Ultramarinas de E.E.U.U" },
  { code: "VI", label: "Islas Vírgenes" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italia" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japón" },
  { code: "JE", label: "Jersey" },
  { code: "JO", label: "Jordania" },
  { code: "KZ", label: "Kazajistán" },
  { code: "KE", label: "Kenia" },
  { code: "KG", label: "Kirguistán" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "LA", label: "Laos, República Democrática" },
  { code: "LS", label: "Lesotho" },
  { code: "LV", label: "Letonia" },
  { code: "LB", label: "Líbano" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libia" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lituania" },
  { code: "LU", label: "Luxemburgo" },
  { code: "MO", label: "Macao" },
  { code: "MK", label: "Macedonia" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malasia" },
  { code: "MW", label: "Malawi" },
  { code: "MV", label: "Maldivas" },
  { code: "ML", label: "Malí" },
  { code: "MT", label: "Malta" },
  { code: "MA", label: "Marruecos" },
  { code: "MQ", label: "Martinica e.a." },
  { code: "MU", label: "Mauricio" },
  { code: "MR", label: "Mauritania" },
  { code: "YT", label: "Mayotte" },
  { code: "MX", label: "México" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldavia, República de" },
  { code: "MC", label: "Mónaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MS", label: "Montserrat" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Níger" },
  { code: "NG", label: "Nigeria" },
  { code: "NU", label: "Niue" },
  { code: "NO", label: "Noruega" },
  { code: "NC", label: "Nueva Caledonia" },
  { code: "NZ", label: "Nueva Zelanda" },
  { code: "OM", label: "Omán" },
  { code: "NL", label: "Países Bajos" },
  { code: "PK", label: "Pakistán" },
  { code: "PW", label: "Palaos" },
  { code: "PS", label: "Palestina" },
  { code: "PA", label: "Panamá" },
  { code: "PG", label: "Papúa, Nueva Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Perú" },
  { code: "PF", label: "Polinesia Francesa" },
  { code: "PL", label: "Polonia" },
  { code: "PT", label: "Portugal" },
  { code: "PR", label: "Puerto Rico" },
  { code: "QA", label: "Qatar" },
  { code: "GB", label: "Reino Unido" },
  { code: "KP", label: "Rep. Democrática popular de Corea" },
  { code: "CZ", label: "República Checa" },
  { code: "KR", label: "República de Corea" },
  { code: "CD", label: "República Democrática del Congo" },
  { code: "DO", label: "República Dominicana" },
  { code: "IR", label: "República Islámica de Irán" },
  { code: "RE", label: "Reunión" },
  { code: "RW", label: "Ruanda" },
  { code: "RO", label: "Rumania" },
  { code: "RU", label: "Rusia" },
  { code: "EH", label: "Sahara Occidental" },
  { code: "BL", label: "Saint Barthélemy" },
  { code: "MF", label: "Saint Martin (French part)" },
  { code: "SB", label: "Salomón, Islas" },
  { code: "WS", label: "Samoa" },
  { code: "AS", label: "Samoa Americana" },
  { code: "KN", label: "San Cristóbal y Nieves" },
  { code: "SM", label: "San Marino" },
  { code: "PM", label: "San ExamplePerson6 y Miquelón" },
  { code: "VC", label: "San Vicente y las Granadinas" },
  { code: "SH", label: "Santa Elena" },
  { code: "LC", label: "Santa Lucía" },
  { code: "ST", label: "Santo Tomé y Príncipe" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leona" },
  { code: "SG", label: "Singapur" },
  { code: "SX", label: "Sint Maarten (Dutch part)" },
  { code: "SY", label: "Siria" },
  { code: "SO", label: "Somalia" },
  { code: "SS", label: "South Sudan" },
  { code: "LK", label: "Sri Lanka" },
  { code: "ZA", label: "Sudáfrica" },
  { code: "SD", label: "Sudán" },
  { code: "SE", label: "Suecia" },
  { code: "CH", label: "Suiza" },
  { code: "SR", label: "Surinám" },
  { code: "SJ", label: "Svalbard y Jan Mayen" },
  { code: "SZ", label: "Swazilandia" },
  { code: "TH", label: "Tailandia" },
  { code: "TW", label: "Taiwan, Provincia de China" },
  { code: "TZ", label: "Tanzania, República Unida de" },
  { code: "TJ", label: "Tayikistán" },
  { code: "IO", label: "Territorio Británico Océano Indico" },
  { code: "TF", label: "Territorios Australes Franceses" },
  { code: "TL", label: "Timor Oriental" },
  { code: "TG", label: "Togo" },
  { code: "TK", label: "Tokelau" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad y Tobago" },
  { code: "TN", label: "Túnez" },
  { code: "TM", label: "Turkmenistán" },
  { code: "TR", label: "Turquía" },
  { code: "TV", label: "Tuvalu" },
  { code: "UA", label: "Ucrania" },
  { code: "UG", label: "Uganda" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistán" },
  { code: "VU", label: "Vanuatu" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "VG", label: "Islas Vírgenes Británicas" },
  { code: "WF", label: "Wallis y Fortuna, Islas" },
  { code: "YE", label: "Yemen" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabue" }
] as const satisfies readonly CatalogOption[];

const cat020CountryCodes = new Set<string>(CAT020_COUNTRIES.map((country) => country.code));

export function normalizeCat020CountryCode(value: string): string {
  return value.trim().toUpperCase();
}

export function isCat020CountryCode(value: unknown): boolean {
  return typeof value === "string" && cat020CountryCodes.has(normalizeCat020CountryCode(value));
}
