export const STRIPE_US_LEGAL_NAME_MAX_LENGTH = 80;
export const STRIPE_US_SIGNER_NAME_MAX_LENGTH = 60;
export const STRIPE_US_SIGNER_TITLE_MAX_LENGTH = 60;
export const STRIPE_US_WEBSITE_MAX_LENGTH = 100;
export const STRIPE_US_MAILING_ADDRESS_LINE_MAX_LENGTH = 80;
